import type { ProjectConfig, SupportedLanguage } from '../types';

export function generateAgentGuide(config: ProjectConfig): string {
  const language: SupportedLanguage = config.cliLanguage ?? 'en';
  const hasBackend = ['api', 'fullstack'].includes(config.type);

  if (language === 'pt') {
    return [
      '# Guia para Agentes de IA',
      '',
      'Este documento fornece orientações para agentes de IA que trabalham neste código.',
      '',
      '## Arquitetura do Projeto',
      '',
      `**Nome:** ${config.projectName}`,
      `**Descrição:** ${config.description}`,
      `**Tipo:** ${config.type}`,
      `**Framework:** ${config.framework}`,
      `**Linguagem:** ${config.language === 'typescript' ? 'TypeScript' : 'JavaScript'}`,
      '',
      '## Estrutura de Pastas',
      '',
      '### Frontend',
      '',
      '```',
      'src/',
      '├── components/     # Componentes React reutilizáveis',
      '├── pages/          # Páginas da aplicação',
      '├── hooks/          # Custom React hooks',
      '├── context/        # Contextos React (Auth, Theme, etc.)',
      '├── services/       # Serviços e chamadas de API',
      '├── styles/         # Estilos globais',
      '├── types/          # Tipos TypeScript',
      '├── utils/          # Funções utilitárias',
      '└── assets/         # Imagens, ícones, fontes',
      '```',
      ...(hasBackend
        ? [
            '',
            '### Backend',
            '',
            '```',
            'src/',
            '├── routes/       # Definição de rotas',
            '├── controllers/  # Controladores de requisição',
            '├── services/     # Lógica de negócio',
            '├── middlewares/  # Middlewares (auth, error handling)',
            '├── utils/        # Utilitários',
            '└── database/     # Configuração do banco de dados',
            '```',
          ]
        : []),
      '',
      '## Convenções de Import',
      '',
      '- Use imports relativos para arquivos dentro de `src`',
      '- Alias `@/` pode ser configurado para apontar para `src/`',
      '- Sempre importe tipos do mesmo arquivo ou de `types/`',
      '',
      '## Contratos de Tipos',
      '',
      '### Componentes',
      '',
      '```typescript',
      'interface ComponentProps {',
      '  className?: string;',
      '  children?: React.ReactNode;',
      '}',
      '```',
      '',
      '### API Responses',
      '',
      '```typescript',
      'interface ApiResponse<T> {',
      '  data: T;',
      '  error?: string;',
      '}',
      '```',
      '',
      '## Checklists de Alteração',
      '',
      '### Antes de Alterar',
      '',
      '- [ ] Entenda o contexto da mudança',
      '- [ ] Identifique todos os arquivos afetados',
      '- [ ] Verifique se há testes existentes',
      '- [ ] Leia documentação relevante (PRD, API.md)',
      '- [ ] Certifique-se de ter as dependências instaladas',
      '',
      '### Durante a Alteração',
      '',
      '- [ ] Mantenha o foco na tarefa (single responsibility)',
      '- [ ] Siga padrões existentes de nomenclatura',
      '- [ ] Use TypeScript corretamente (sem `any`)',
      '- [ ] Escreva código legível e comentado quando necessário',
      '- [ ] Adicione testes para novas funcionalidades',
      '- [ ] Atualize documentação se necessário',
      '',
      '### Após a Alteração',
      '',
      '- [ ] Execute `npm run lint` e corrija erros',
      '- [ ] Execute `npm run build` para verificar tipos',
      '- [ ] Execute `npm test` e garanta que todos passam',
      '- [ ] Execute `npm run test:e2e` para testes end-to-end',
      '- [ ] Verifique se não há console.log deixados',
      '- [ ] Revise a mudança com git diff',
      '',
      '## Regras de Segurança para LLMs',
      '',
      '### NUNCA modifique automaticamente:',
      '',
      '- `.env` ou arquivos com secrets',
      '- `package-lock.json` sem necessidade explícita',
      '- Arquivos de migração do banco de dados',
      '- Configurações de produção sem confirmação',
      '- Chaves de API, senhas, tokens',
      '',
      '### SEMPRE:',
      '',
      '- Valide que variáveis de ambiente sensíveis estão configuradas',
      '- Use `process.env` para secrets',
      '- Nunca faça commit de `.env`',
      '- Siga o princípio do menor privilégio',
      '',
      '### Ao lidar com autenticação:',
      '',
      '- Nunca exponha tokens no client-side',
      '- Use HTTPS para todas as requisições',
      '- Valide tokens no backend',
      '- Implemente rate limiting',
      '',
      '## Padrões de Commit',
      '',
      'Use [Conventional Commits](https://www.conventionalcommits.org/):',
      '',
      '```',
      '<tipo>(<escopo>): <descrição>',
      '',
      '<corpo opcional>',
      '',
      '<rodapé opcional>',
      '```',
      '',
      '### Tipos:',
      '',
      '- `feat`: Nova funcionalidade',
      '- `fix`: Correção de bug',
      '- `docs`: Mudanças na documentação',
      '- `style`: Formatação, missing semi-colons, etc',
      '- `refactor`: Refatoração de código',
      '- `test`: Adicionar ou corrigir testes',
      '- `chore`: Mudanças no build process, ferramentas, etc',
      '',
      '### Exemplos:',
      '',
      '```',
      'feat(auth): add password reset functionality',
      'fix(api): handle null case in user service',
      'docs(readme): update installation instructions',
      'test(components): add unit tests for Button component',
      '```',
      '',
      '## Padrões de Pull Request',
      '',
      '### Título do PR:',
      '',
      'Siga o mesmo padrão de commits: `<tipo>(<escopo>): <descrição>`',
      '',
      '### Descrição do PR:',
      '',
      '```markdown',
      '## O que foi feito',
      '',
      'Breve descrição das mudanças.',
      '',
      '## Por que foi feito',
      '',
      'Contexto e justificativa.',
      '',
      '## Como testar',
      '',
      'Passos para testar as mudanças.',
      '',
      '## Checklist',
      '',
      '- [ ] Testes passando',
      '- [ ] Lint passando',
      '- [ ] Build passando',
      '- [ ] Documentação atualizada',
      '```',
      '',
      '## Fluxos de Trabalho Típicos',
      '',
      '### Adicionar Nova Página',
      '',
      '1. Crie o componente em `src/pages/`',
      '2. Adicione a rota no router',
      '3. Crie testes de renderização',
      '4. Adicione meta tags SEO',
      '5. Teste navegação',
      '',
      '### Adicionar Novo Componente',
      '',
      '1. Crie em `src/components/`',
      '2. Adicione estilos conforme Design System',
      '3. Crie testes unitários',
      '4. Documente props',
      '5. Exporte do index',
      '',
      '### Adicionar Endpoint de API',
      '',
      '1. Defina a rota em `src/routes/`',
      '2. Crie o controller em `src/controllers/`',
      '3. Implemente o service em `src/services/`',
      '4. Adicione testes unitários e de integração',
      '5. Documente em `docs/API.md`',
      '',
      '## Ferramentas de QA',
      '',
      '- **Vitest**: Testes unitários',
      '- **Playwright**: Testes E2E',
      '- **Biome**: Linting e formatação',
      '- **TypeScript**: Type checking',
      '- **Lighthouse**: Performance e acessibilidade',
      '',
    ].join('\n');
  }

  if (language === 'es') {
    return [
      '# Guía para Agentes de IA',
      '',
      'Este documento proporciona orientación para agentes de IA que trabajan en este código.',
      '',
      '## Arquitectura del Proyecto',
      '',
      `**Nombre:** ${config.projectName}`,
      `**Descripción:** ${config.description}`,
      '',
      '## Convenciones de Importación',
      '',
      '- Use imports relativos para archivos dentro de `src`',
      '- Alias `@/` puede configurarse para apuntar a `src/`',
      '',
      '## Checklists de Modificación',
      '',
      '### Antes de Modificar',
      '',
      '- [ ] Entienda el contexto del cambio',
      '- [ ] Identifique todos los archivos afectados',
      '- [ ] Verifique si hay pruebas existentes',
      '',
      '### Durante la Modificación',
      '',
      '- [ ] Mantenga el foco en la tarea',
      '- [ ] Siga patrones existentes',
      '- [ ] Use TypeScript correctamente (sin `any`)',
      '- [ ] Agregue pruebas para nuevas funcionalidades',
      '',
      '### Después de la Modificación',
      '',
      '- [ ] Ejecute `npm run lint`',
      '- [ ] Ejecute `npm run build`',
      '- [ ] Ejecute `npm test`',
      '',
      '## Reglas de Seguridad para LLMs',
      '',
      '### NUNCA modifique automáticamente:',
      '',
      '- `.env` o archivos con secrets',
      '- `package-lock.json` sin necesidad',
      '- Archivos de migración de base de datos',
      '- Chaves de API, contraseñas, tokens',
      '',
      '## Patrones de Commit',
      '',
      'Use [Conventional Commits](https://www.conventionalcommits.org/):',
      '',
      '```',
      '<tipo>(<alcance>): <descripción>',
      '```',
      '',
      '### Tipos:',
      '',
      '- `feat`: Nueva funcionalidad',
      '- `fix`: Corrección de bug',
      '- `docs`: Cambios en documentación',
      '- `test`: Agregar o corregir pruebas',
      '- `refactor`: Refactorización',
      '',
    ].join('\n');
  }

  return [
    '# AI Agent Guide',
    '',
    'This document provides guidance for AI agents working on this codebase.',
    '',
    '## Project Architecture',
    '',
    `**Name:** ${config.projectName}`,
    `**Description:** ${config.description}`,
    `**Type:** ${config.type}`,
    `**Framework:** ${config.framework}`,
    `**Language:** ${config.language === 'typescript' ? 'TypeScript' : 'JavaScript'}`,
    '',
    '## Folder Structure',
    '',
    '### Frontend',
    '',
    '```',
    'src/',
    '├── components/     # Reusable React components',
    '├── pages/          # Application pages',
    '├── hooks/          # Custom React hooks',
    '├── context/        # React contexts (Auth, Theme, etc.)',
    '├── services/       # API services and calls',
    '├── styles/         # Global styles',
    '├── types/          # TypeScript types',
    '├── utils/          # Utility functions',
    '└── assets/         # Images, icons, fonts',
    '```',
    ...(hasBackend
      ? [
          '',
          '### Backend',
          '',
          '```',
          'src/',
          '├── routes/       # Route definitions',
          '├── controllers/  # Request controllers',
          '├── services/     # Business logic',
          '├── middlewares/  # Middlewares (auth, error handling)',
          '├── utils/        # Utilities',
          '└── database/     # Database configuration',
          '```',
        ]
      : []),
    '',
    '## Import Conventions',
    '',
    '- Use relative imports for files within `src`',
    '- Alias `@/` can be configured to point to `src/`',
    '- Always import types from the same file or from `types/`',
    '',
    '## Type Contracts',
    '',
    '### Components',
    '',
    '```typescript',
    'interface ComponentProps {',
    '  className?: string;',
    '  children?: React.ReactNode;',
    '}',
    '```',
    '',
    '### API Responses',
    '',
    '```typescript',
    'interface ApiResponse<T> {',
    '  data: T;',
    '  error?: string;',
    '}',
    '```',
    '',
    '## Modification Checklists',
    '',
    '### Before Making Changes',
    '',
    '- [ ] Understand the context of the change',
    '- [ ] Identify all affected files',
    '- [ ] Check for existing tests',
    '- [ ] Read relevant documentation (PRD, API.md)',
    '- [ ] Ensure dependencies are installed',
    '',
    '### During Changes',
    '',
    '- [ ] Keep focus on the task (single responsibility)',
    '- [ ] Follow existing naming patterns',
    '- [ ] Use TypeScript correctly (no `any`)',
    '- [ ] Write readable and commented code when needed',
    '- [ ] Add tests for new features',
    '- [ ] Update documentation if needed',
    '',
    '### After Changes',
    '',
    '- [ ] Run `npm run lint` and fix errors',
    '- [ ] Run `npm run build` to check types',
    '- [ ] Run `npm test` and ensure all pass',
    '- [ ] Run `npm run test:e2e` for end-to-end tests',
    '- [ ] Check for no console.log left behind',
    '- [ ] Review changes with git diff',
    '',
    '## Security Rules for LLMs',
    '',
    '### NEVER automatically modify:',
    '',
    '- `.env` or files with secrets',
    '- `package-lock.json` without explicit need',
    '- Database migration files',
    '- Production configurations without confirmation',
    '- API keys, passwords, tokens',
    '',
    '### ALWAYS:',
    '',
    '- Validate that sensitive environment variables are configured',
    '- Use `process.env` for secrets',
    '- Never commit `.env`',
    '- Follow the principle of least privilege',
    '',
    '### When handling authentication:',
    '',
    '- Never expose tokens on client-side',
    '- Use HTTPS for all requests',
    '- Validate tokens on backend',
    '- Implement rate limiting',
    '',
    '## Commit Standards',
    '',
    'Use [Conventional Commits](https://www.conventionalcommits.org/):',
    '',
    '```',
    '<type>(<scope>): <description>',
    '',
    '<optional body>',
    '',
    '<optional footer>',
    '```',
    '',
    '### Types:',
    '',
    '- `feat`: New feature',
    '- `fix`: Bug fix',
    '- `docs`: Documentation changes',
    '- `style`: Formatting, missing semi-colons, etc',
    '- `refactor`: Code refactoring',
    '- `test`: Adding or fixing tests',
    '- `chore`: Build process, tools, etc',
    '',
    '### Examples:',
    '',
    '```',
    'feat(auth): add password reset functionality',
    'fix(api): handle null case in user service',
    'docs(readme): update installation instructions',
    'test(components): add unit tests for Button component',
    '```',
    '',
    '## Pull Request Standards',
    '',
    '### PR Title:',
    '',
    'Follow the same pattern as commits: `<type>(<scope>): <description>`',
    '',
    '### PR Description:',
    '',
    '```markdown',
    '## What was done',
    '',
    'Brief description of changes.',
    '',
    '## Why it was done',
    '',
    'Context and justification.',
    '',
    '## How to test',
    '',
    'Steps to test the changes.',
    '',
    '## Checklist',
    '',
    '- [ ] Tests passing',
    '- [ ] Lint passing',
    '- [ ] Build passing',
    '- [ ] Documentation updated',
    '```',
    '',
    '## Typical Workflows',
    '',
    '### Add New Page',
    '',
    '1. Create component in `src/pages/`',
    '2. Add route to router',
    '3. Create render tests',
    '4. Add SEO meta tags',
    '5. Test navigation',
    '',
    '### Add New Component',
    '',
    '1. Create in `src/components/`',
    '2. Add styles per Design System',
    '3. Create unit tests',
    '4. Document props',
    '5. Export from index',
    '',
    '### Add API Endpoint',
    '',
    '1. Define route in `src/routes/`',
    '2. Create controller in `src/controllers/`',
    '3. Implement service in `src/services/`',
    '4. Add unit and integration tests',
    '5. Document in `docs/API.md`',
    '',
    '## QA Tools',
    '',
    '- **Vitest**: Unit testing',
    '- **Playwright**: E2E testing',
    '- **Biome**: Linting and formatting',
    '- **TypeScript**: Type checking',
    '- **Lighthouse**: Performance and accessibility',
    '',
  ].join('\n');
}
