import type { ProjectConfig, SupportedLanguage } from '../types';

export function generateArchitectureDoc(config: ProjectConfig): string {
  const language: SupportedLanguage = config.cliLanguage ?? 'en';

  if (language === 'pt') {
    return [
      '# Arquitetura do Projeto',
      '',
      '## Visão Geral',
      '',
      `Este documento descreve a arquitetura e a estrutura do projeto **${config.projectName}**.`,
      '',
      '## Stack de Tecnologia',
      '',
      `- **Frontend:** ${config.framework}`,
      `- **Linguagem:** ${config.language === 'typescript' ? 'TypeScript' : 'JavaScript'}`,
      `- **Estilização:** ${config.styling}`,
      config.database ? `- **Banco de Dados:** ${config.database}` : '',
      '',
      '## Estrutura de Pastas',
      '',
      '```',
      'src/',
      '├── components/     # Componentes React reutilizáveis',
      '├── pages/          # Páginas da aplicação',
      '├── hooks/          # Custom React hooks',
      '├── context/        # Contextos React (Auth, Theme, etc.)',
      '├── services/       # Serviços e chamadas de API',
      '├── styles/         # Estilos globais e variáveis CSS',
      '├── types/          # Tipos TypeScript',
      '├── utils/          # Funções utilitárias',
      '└── assets/         # Imagens, ícones, fontes',
      '```',
      '',
      '## Padrões de Código',
      '',
      '### Componentes',
      '',
      '- Componentes funcionais com React Hooks',
      '- TypeScript para segurança de tipos',
      '- Styled Components/Tailwind para estilização',
      '- Testes unitários com Vitest + Testing Library',
      '',
      '### Nomenclatura',
      '',
      '- Componentes: PascalCase (ex.: `Button.tsx`)',
      '- Hooks: camelCase com prefixo `use` (ex.: `useAuth.ts`)',
      '- Utils: camelCase (ex.: `formatDate.ts`)',
      '- Tipos: PascalCase (ex.: `User.ts`)',
      '',
      '## Fluxo de Dados',
      '',
      '1. Componentes consomem dados via hooks',
      '2. Hooks chamam serviços',
      '3. Serviços fazem requisições HTTP pelo cliente de API',
      '4. Estado global gerenciado via Context API',
      '',
      '## Boas Práticas',
      '',
      '- Componentes pequenos e focados em uma única responsabilidade',
      '- Extrair lógica repetida para hooks personalizados',
      '- Usar TypeScript em modo estrito',
      '- Escrever testes para componentes e hooks críticos',
      '- Usar code splitting para rotas pesadas',
      '',
    ].join('\n');
  }

  if (language === 'es') {
    return [
      '# Arquitectura del Proyecto',
      '',
      '## Visión General',
      '',
      `Este documento describe la arquitectura y estructura del proyecto **${config.projectName}**.`,
      '',
      '## Stack de Tecnología',
      '',
      `- **Frontend:** ${config.framework}`,
      `- **Lenguaje:** ${config.language === 'typescript' ? 'TypeScript' : 'JavaScript'}`,
      `- **Estilos:** ${config.styling}`,
      config.database ? `- **Base de Datos:** ${config.database}` : '',
      '',
      '## Estructura de Carpetas',
      '',
      '```',
      'src/',
      '├── components/     # Componentes React reutilizables',
      '├── pages/          # Páginas de la aplicación',
      '├── hooks/          # Custom React hooks',
      '├── context/        # Contextos React (Auth, Theme, etc.)',
      '├── services/       # Servicios y llamadas a la API',
      '├── styles/         # Estilos globales y variables CSS',
      '├── types/          # Tipos de TypeScript',
      '├── utils/          # Funciones utilitarias',
      '└── assets/         # Imágenes, íconos, fuentes',
      '```',
      '',
      '## Estándares de Código',
      '',
      '### Componentes',
      '',
      '- Componentes funcionales con React Hooks',
      '- TypeScript para seguridad de tipos',
      '- Styled Components/Tailwind para estilos',
      '- Tests unitarios con Vitest + Testing Library',
      '',
      '### Nomenclatura',
      '',
      '- Componentes: PascalCase (ej.: `Button.tsx`)',
      '- Hooks: camelCase con prefijo `use` (ej.: `useAuth.ts`)',
      '- Utils: camelCase (ej.: `formatDate.ts`)',
      '- Tipos: PascalCase (ej.: `User.ts`)',
      '',
      '## Flujo de Datos',
      '',
      '1. Los componentes consumen datos mediante hooks',
      '2. Los hooks llaman a los servicios',
      '3. Los servicios realizan peticiones HTTP a través del cliente de API',
      '4. El estado global se gestiona mediante Context API',
      '',
      '## Buenas Prácticas',
      '',
      '- Componentes pequeños y enfocados en una sola responsabilidad',
      '- Extraer lógica repetida a hooks personalizados',
      '- Usar TypeScript en modo estricto',
      '- Escribir tests para componentes y hooks críticos',
      '- Usar code splitting para rutas pesadas',
      '',
    ].join('\n');
  }

  return [
    '# Project Architecture',
    '',
    '## Overview',
    '',
    `This document describes the architecture and structure of the **${config.projectName}** project.`,
    '',
    '## Technology Stack',
    '',
    `- **Frontend:** ${config.framework}`,
    `- **Language:** ${config.language === 'typescript' ? 'TypeScript' : 'JavaScript'}`,
    `- **Styling:** ${config.styling}`,
    config.database ? `- **Database:** ${config.database}` : '',
    '',
    '## Folder Structure',
    '',
    '```',
    'src/',
    '├── components/     # Reusable React components',
    '├── pages/          # Application pages',
    '├── hooks/          # Custom React hooks',
    '├── context/        # React contexts (Auth, Theme, etc.)',
    '├── services/       # Services and API calls',
    '├── styles/         # Global styles and CSS variables',
    '├── types/          # TypeScript types',
    '├── utils/          # Utility functions',
    '└── assets/         # Images, icons, fonts',
    '```',
    '',
    '## Code Standards',
    '',
    '### Components',
    '',
    '- Functional components with React Hooks',
    '- TypeScript for type safety',
    '- Styled Components/Tailwind for styling',
    '- Unit tests with Vitest + Testing Library',
    '',
    '### Naming',
    '',
    '- Components: PascalCase (e.g. `Button.tsx`)',
    '- Hooks: camelCase with `use` prefix (e.g. `useAuth.ts`)',
    '- Utils: camelCase (e.g. `formatDate.ts`)',
    '- Types: PascalCase (e.g. `User.ts`)',
    '',
    '## Data Flow',
    '',
    '1. Components consume data via hooks',
    '2. Hooks call services',
    '3. Services perform HTTP requests through the API client',
    '4. Global state managed via Context API',
    '',
    '## Best Practices',
    '',
    '- Small, focused components with a single responsibility',
    '- Extract repeated logic to custom hooks',
    '- Use TypeScript in strict mode',
    '- Write unit tests for critical components and hooks',
    '- Use code splitting for heavy routes',
    '',
  ].join('\n');
}
