import type { ProjectConfig, SupportedLanguage } from '../types';

export function generateQaGuide(config: ProjectConfig): string {
  const language: SupportedLanguage = config.cliLanguage ?? 'en';

  if (language === 'pt') {
    return [
      '# Guia de QA e Testes',
      '',
      `Este documento resume como validar a qualidade do projeto **${config.projectName}**.`,
      '',
      '## Scripts Disponíveis',
      '',
      'No frontend:',
      '',
      '- `npm run test` – Roda testes unitários com Vitest',
      '- `npm run test:watch` – Roda testes em modo watch',
      '- `npm run test:coverage` – Gera relatório de cobertura (threshold global ~80%)',
      '- `npm run test:e2e` – Roda testes E2E com Playwright (requer servidor em execução)',
      '',
      'No backend:',
      '',
      '- `npm run test` – Roda testes (unitários e de integração) com Vitest',
      '- `npm run test:watch` – Watch mode',
      '- `npm run test:coverage` – Cobertura com Vitest',
      '',
      '## Testes E2E (Frontend)',
      '',
      'Os testes E2E ficam em `frontend/tests/e2e` e usam Playwright.',
      '',
      '1. Inicie o servidor de desenvolvimento do frontend:',
      '',
      '- `npm run dev` dentro da pasta `frontend`',
      '',
      '2. Em outro terminal, rode:',
      '',
      '- `npm run test:e2e`',
      '',
      'Os arquivos `auth.spec.ts` e `navigation.spec.ts` trazem exemplos básicos de fluxo de autenticação (UI) e navegação.',
      '',
      '## Testes de Backend',
      '',
      'Os testes do backend ficam em `backend/tests`:',
      '',
      '- `unit/` – exemplos para services (`auth.service`, `user.service`)',
      '- `integration/` – exemplo de teste de rota (`/health`) com supertest',
      '',
      'Alguns testes vêm marcados como `skip` ou `todo` para evitar falhas sem um banco de dados de testes configurado.',
      '',
      '## Próximos Passos para o Time / Agente de IA',
      '',
      '- Completar os testes marcados como `skip`/`todo` assim que o domínio e o banco estiverem configurados',
      '- Manter a cobertura de testes acima dos thresholds configurados',
      '- Adicionar testes para novos componentes, hooks, serviços e rotas seguindo os exemplos existentes',
      '',
    ].join('\n');
  }

  if (language === 'es') {
    return [
      '# Guía de QA y Tests',
      '',
      `Este documento resume cómo validar la calidad del proyecto **${config.projectName}**.`,
      '',
      '## Scripts Disponibles',
      '',
      'Frontend:',
      '',
      '- `npm run test` – Tests unitarios con Vitest',
      '- `npm run test:watch` – Modo watch',
      '- `npm run test:coverage` – Cobertura (~80% global)',
      '- `npm run test:e2e` – Tests E2E con Playwright',
      '',
      'Backend:',
      '',
      '- `npm run test` – Tests unitarios/integración con Vitest',
      '- `npm run test:watch` – Modo watch',
      '- `npm run test:coverage` – Cobertura con Vitest',
      '',
      '## Tests E2E (Frontend)',
      '',
      'Los tests E2E están en `frontend/tests/e2e` y usan Playwright.',
      '',
      '1. Iniciar el servidor de desarrollo en `frontend` con `npm run dev`',
      '2. Ejecutar `npm run test:e2e` en otra terminal',
      '',
      '## Tests de Backend',
      '',
      'Los tests se encuentran en `backend/tests` (unit e integration).',
      '',
      'Algunos tests están marcados como `skip`/`todo` hasta que exista una base de datos de pruebas configurada.',
      '',
    ].join('\n');
  }

  return [
    '# QA and Testing Guide',
    '',
    `This document summarizes how to validate the quality of **${config.projectName}**.`,
    '',
    '## Available Scripts',
    '',
    'Frontend:',
    '',
    '- `npm run test` – Run unit tests with Vitest',
    '- `npm run test:watch` – Run tests in watch mode',
    '- `npm run test:coverage` – Generate coverage report (global threshold ~80%)',
    '- `npm run test:e2e` – Run E2E tests with Playwright (requires dev server running)',
    '',
    'Backend:',
    '',
    '- `npm run test` – Run unit and integration tests with Vitest',
    '- `npm run test:watch` – Watch mode',
    '- `npm run test:coverage` – Coverage with Vitest',
    '',
    '## Frontend E2E Tests',
    '',
    'E2E tests live in `frontend/tests/e2e` and use Playwright.',
    '',
    '1. Start the frontend dev server with `npm run dev` inside `frontend`',
    '2. In another terminal, run `npm run test:e2e`',
    '',
    'The files `auth.spec.ts` and `navigation.spec.ts` contain basic examples.',
    '',
    '## Backend Tests',
    '',
    'Backend tests live in `backend/tests`:',
    '',
    '- `unit/` – examples for services (`auth.service`, `user.service`)',
    '- `integration/` – example route test (`/health`) with supertest',
    '',
    'Some tests are marked as `skip` or `todo` so they do not fail before a dedicated test database is configured.',
    '',
    '## Next Steps for the Team / AI Agent',
    '',
    '- Complete skipped/todo tests once domain and database are configured',
    '- Keep coverage above the configured thresholds',
    '- Add tests for new components, hooks, services and routes following the existing examples',
    '',
  ].join('\n');
}

export function generateAccessibilityDoc(config: ProjectConfig): string {
  const language: SupportedLanguage = config.cliLanguage ?? 'en';

  if (language === 'pt') {
    return [
      '# Acessibilidade',
      '',
      `Este documento traz um checklist básico de acessibilidade para o projeto **${config.projectName}**.`,
      '',
      '## Checklist rápido',
      '',
      '- Todas as imagens possuem `alt` descritivo.',
      '- Conteúdo é navegável apenas com teclado (Tab, Shift+Tab, Enter, Space).',
      '- Foco visível em links, botões e elementos interativos.',
      '- Contraste de cores atende ao mínimo recomendado (WCAG AA).',
      '- Componentes complexos utilizam atributos ARIA quando necessário.',
      '',
      '## Recomendações',
      '',
      '- Use Lighthouse para checar acessibilidade a cada release.',
      '- Teste fluxos críticos com leitor de tela e navegação por teclado.',
      '',
    ].join('\n');
  }

  if (language === 'es') {
    return [
      '# Accesibilidad',
      '',
      `Este documento presenta un checklist básico de accesibilidad para el proyecto **${config.projectName}**.`,
      '',
      '## Checklist rápido',
      '',
      '- Todas las imágenes tienen atributo `alt` descriptivo.',
      '- El contenido es navegable solo con teclado (Tab, Shift+Tab, Enter, Space).',
      '- El foco es visible en enlaces, botones y elementos interactivos.',
      '- El contraste de color cumple al menos con WCAG AA.',
      '- Los componentes complejos usan atributos ARIA cuando es necesario.',
      '',
      '## Recomendaciones',
      '',
      '- Usa Lighthouse para revisar accesibilidad en cada release.',
      '- Prueba flujos críticos con lector de pantalla y navegación por teclado.',
      '',
    ].join('\n');
  }

  return [
    '# Accessibility',
    '',
    `This document provides a basic accessibility checklist for the **${config.projectName}** project.`,
    '',
    '## Quick checklist',
    '',
    '- All images include descriptive `alt` text.',
    '- Content is fully navigable with keyboard only (Tab, Shift+Tab, Enter, Space).',
    '- Focus is visible on links, buttons and interactive elements.',
    '- Color contrast meets at least WCAG AA guidelines.',
    '- Complex components use ARIA attributes when needed.',
    '',
    '## Recommendations',
    '',
    '- Use Lighthouse to audit accessibility on each release.',
    '- Test critical flows with screen readers and keyboard navigation.',
    '',
  ].join('\n');
}
