import type { ProjectConfig, SupportedLanguage } from '../types';

export function generateReadme(config: ProjectConfig): string {
  const hasBackend = ['api', 'fullstack'].includes(config.type);
  const language: SupportedLanguage = config.cliLanguage ?? 'en';

  if (language === 'pt') {
    return generateReadmePt(config, hasBackend);
  }

  if (language === 'es') {
    return generateReadmeEs(config, hasBackend);
  }

  return generateReadmeEn(config, hasBackend);
}

function generateReadmePt(config: ProjectConfig, hasBackend: boolean): string {
  return [
    `# ${config.projectName}`,
    '',
    config.description,
    '',
    '## 🚀 Começando',
    '',
    '### Pré-requisitos',
    '',
    '- Node.js 18+',
    '- npm/yarn/pnpm',
    '',
    '### Instalação',
    '',
    '```bash',
    '# Instalar dependências',
    'npm install',
    '',
    '# Iniciar servidor de desenvolvimento',
    'npm run dev',
    '```',
    '',
    '## 📁 Estrutura do Projeto',
    '',
    '```',
    'src/',
    '├── components/     # Componentes reutilizáveis',
    '├── pages/          # Páginas da aplicação',
    '├── hooks/          # Custom React hooks',
    '├── context/        # Contextos React',
    '├── services/       # Serviços e chamadas de API',
    '├── styles/         # Estilos globais',
    '├── types/          # Tipos TypeScript',
    '├── utils/          # Funções utilitárias',
    '└── assets/         # Imagens, ícones, fontes',
    '```',
    '',
    '## 🛠️ Stack Técnica',
    '',
    `- **Framework:** ${config.framework}`,
    `- **Linguagem:** ${config.language === 'typescript' ? 'TypeScript' : 'JavaScript'}`,
    `- **Estilização:** ${config.styling}`,
    config.database ? `- **Banco de Dados:** ${config.database}` : '',
    '',
    '## 📋 Scripts Disponíveis',
    '',
    '- `npm run dev` - Inicia o servidor de desenvolvimento',
    '- `npm run build` - Gera build de produção',
    '- `npm run preview` - Preview do build de produção',
    '- `npm run lint` - Executa ESLint',
    '- `npm run test` - Executa testes',
    '',
    '## ⚡ Performance e Monitoramento',
    '',
    '- Use o Lighthouse (no Chrome DevTools) para auditar performance, acessibilidade e SEO.',
    '- Acompanhe Web Vitals (LCP, FID, CLS) durante o desenvolvimento e antes de releases.',
    '',
    '## 📖 Documentação',
    '',
    '- [PRD](./docs/PRD.md) - Documento de Requisitos de Produto',
    '- [Design System](./docs/DESIGN_SYSTEM.md)',
    '- [Arquitetura](./docs/ARCHITECTURE.md)',
    hasBackend ? '- [Documentação da API](./docs/API.md)' : '',
    '- [Guia para Agentes de IA](./docs/AGENT_GUIDE.md) - Guia para agentes de IA trabalhando no código',
    '- [Release Checklist](./docs/RELEASE_CHECKLIST.md) - Checklist de pré-release e deploy',
    '',
    '## 👥 Onboarding da Equipe',
    '',
    '### Primeiros Passos',
    '',
    '1. Clone o repositório',
    '2. Execute `npm install` para instalar dependências',
    '3. Copie `.env.example` para `.env` e preencha os valores',
    '4. Execute `npm run dev` para iniciar o servidor de desenvolvimento',
    '5. Leia o [Guia para Agentes de IA](./docs/AGENT_GUIDE.md) para entender a arquitetura e convenções',
    '',
    '### Fluxo de Desenvolvimento',
    '',
    '1. Crie uma branch para sua feature ou bugfix',
    '2. Faça suas mudanças seguindo os padrões de código',
    '3. Execute `npm run lint` para verificar erros de lint',
    '4. Execute `npm test` para garantir que todos os testes passam',
    '5. Execute `npm run build` para verificar tipos TypeScript',
    '6. Faça commit das mudanças usando [Conventional Commits](https://www.conventionalcommits.org/)',
    '7. Faça push e abra um Pull Request',
    '',
    '### Pipeline de CI/CD',
    '',
    'Este projeto usa GitHub Actions para integração e deploy contínuos. A cada push na `main` ou `develop`, o pipeline vai:',
    '',
    '- Instalar dependências',
    '- Rodar lint checks',
    '- Rodar testes unitários e de integração',
    '- Fazer build do projeto',
    '- Upload dos relatórios de coverage',
    '',
    'Veja `.github/workflows/ci-cd.yml` para a configuração completa do pipeline.',
    '',
    '## 🤝 Contribuindo',
    '',
    '1. Faça um fork do repositório',
    '2. Crie sua branch de feature',
    '3. Faça commit das mudanças',
    '4. Envie para sua branch',
    '5. Abra um Pull Request',
    '',
    '## 📄 Licença',
    '',
    'MIT License',
    '',
  ].join('\n');
}

function generateReadmeEs(config: ProjectConfig, hasBackend: boolean): string {
  return [
    `# ${config.projectName}`,
    '',
    config.description,
    '',
    '## 🚀 Empezando',
    '',
    '### Prerrequisitos',
    '',
    '- Node.js 18+',
    '- npm/yarn/pnpm',
    '',
    '### Instalación',
    '',
    '```bash',
    '# Instalar dependencias',
    'npm install',
    '',
    '# Iniciar servidor de desarrollo',
    'npm run dev',
    '```',
    '',
    '## 📁 Estructura del Proyecto',
    '',
    '```',
    'src/',
    '├── components/     # Componentes reutilizables',
    '├── pages/          # Páginas de la aplicación',
    '├── hooks/          # Custom React hooks',
    '├── context/        # Contextos React',
    '├── services/       # Servicios y llamadas a API',
    '├── styles/         # Estilos globales',
    '├── types/          # Tipos de TypeScript',
    '├── utils/          # Funciones utilitarias',
    '└── assets/         # Imágenes, íconos, fuentes',
    '```',
    '',
    '## 🛠️ Stack Técnico',
    '',
    `- **Framework:** ${config.framework}`,
    `- **Lenguaje:** ${config.language === 'typescript' ? 'TypeScript' : 'JavaScript'}`,
    `- **Estilos:** ${config.styling}`,
    config.database ? `- **Base de Datos:** ${config.database}` : '',
    '',
    '## 📋 Scripts Disponibles',
    '',
    '- `npm run dev` - Inicia el servidor de desarrollo',
    '- `npm run build` - Genera el build de producción',
    '- `npm run preview` - Preview del build de producción',
    '- `npm run lint` - Ejecuta ESLint',
    '- `npm run test` - Ejecuta tests',
    '',
    '## ⚡ Rendimiento y Monitoreo',
    '',
    '- Usa Lighthouse (en Chrome DevTools) para auditar rendimiento, accesibilidad y SEO.',
    '- Monitoriza Web Vitals (LCP, FID, CLS) durante el desarrollo y antes de releases.',
    '',
    '## 📖 Documentación',
    '',
    '- [PRD](./docs/PRD.md) - Documento de Requisitos de Producto',
    '- [Design System](./docs/DESIGN_SYSTEM.md)',
    '- [Arquitectura](./docs/ARCHITECTURE.md)',
    hasBackend ? '- [Documentación de la API](./docs/API.md)' : '',
    '- [Guía para Agentes de IA](./docs/AGENT_GUIDE.md) - Guía para agentes de IA trabajando en el código',
    '- [Release Checklist](./docs/RELEASE_CHECKLIST.md) - Checklist de pre-release y deploy',
    '',
    '## 👥 Onboarding del Equipo',
    '',
    '### Primeros Pasos',
    '',
    '1. Clona el repositorio',
    '2. Ejecuta `npm install` para instalar dependencias',
    '3. Copia `.env.example` a `.env` y completa los valores',
    '4. Ejecuta `npm run dev` para iniciar el servidor de desarrollo',
    '5. Lee la [Guía para Agentes de IA](./docs/AGENT_GUIDE.md) para entender la arquitectura y convenciones',
    '',
    '### Flujo de Desarrollo',
    '',
    '1. Crea una rama para tu feature o bugfix',
    '2. Haz tus cambios siguiendo los estándares de código',
    '3. Ejecuta `npm run lint` para verificar errores de lint',
    '4. Ejecuta `npm test` para asegurar que todas las pruebas pasan',
    '5. Ejecuta `npm run build` para verificar tipos TypeScript',
    '6. Haz commit de tus cambios usando [Conventional Commits](https://www.conventionalcommits.org/)',
    '7. Haz push y abre un Pull Request',
    '',
    '### Pipeline de CI/CD',
    '',
    'Este proyecto usa GitHub Actions para integración y deploy continuos. En cada push a `main` o `develop`, el pipeline va:',
    '',
    '- Instalar dependencias',
    '- Ejecutar lint checks',
    '- Ejecutar pruebas unitarias y de integración',
    '- Compilar el proyecto',
    '- Upload de reportes de coverage',
    '',
    'Ver `.github/workflows/ci-cd.yml` para la configuración completa del pipeline.',
    '',
    '## 🤝 Contribuir',
    '',
    '1. Haz un fork del repositorio',
    '2. Crea tu rama de feature',
    '3. Haz commit de tus cambios',
    '4. Haz push a la rama',
    '5. Abre un Pull Request',
    '',
    '## 📄 Licencia',
    '',
    'MIT License',
    '',
  ].join('\n');
}

function generateReadmeEn(config: ProjectConfig, hasBackend: boolean): string {
  return [
    `# ${config.projectName}`,
    '',
    config.description,
    '',
    '## 🚀 Getting Started',
    '',
    '### Prerequisites',
    '',
    '- Node.js 18+',
    '- npm/yarn/pnpm',
    '',
    '### Installation',
    '',
    '```bash',
    '# Install dependencies',
    'npm install',
    '',
    '# Start development server',
    'npm run dev',
    '```',
    '',
    '## 📁 Project Structure',
    '',
    '```',
    'src/',
    '├── components/     # Reusable components',
    '├── pages/          # Application pages',
    '├── hooks/          # Custom React hooks',
    '├── context/        # React contexts',
    '├── services/       # Services and API calls',
    '├── styles/         # Global styles',
    '├── types/          # TypeScript types',
    '├── utils/          # Utility functions',
    '└── assets/         # Images, icons, fonts',
    '```',
    '',
    '## 🛠️ Tech Stack',
    '',
    `- **Framework:** ${config.framework}`,
    `- **Language:** ${config.language === 'typescript' ? 'TypeScript' : 'JavaScript'}`,
    `- **Styling:** ${config.styling}`,
    config.database ? `- **Database:** ${config.database}` : '',
    '',
    '## 📋 Available Scripts',
    '',
    '- `npm run dev` - Start development server',
    '- `npm run build` - Build for production',
    '- `npm run preview` - Preview production build',
    '- `npm run lint` - Run ESLint',
    '- `npm run test` - Run tests',
    '',
    '## ⚡ Performance and Monitoring',
    '',
    '- Use Lighthouse (in Chrome DevTools) to audit performance, accessibility and SEO.',
    '- Track Web Vitals (LCP, FID, CLS) during development and before releases.',
    '',
    '## 📖 Documentation',
    '',
    '- [PRD](./docs/PRD.md) - Product Requirements Document',
    '- [Design System](./docs/DESIGN_SYSTEM.md)',
    '- [Architecture](./docs/ARCHITECTURE.md)',
    hasBackend ? '- [API Documentation](./docs/API.md)' : '',
    '- [AI Agent Guide](./docs/AGENT_GUIDE.md) - Guide for AI agents working on this codebase',
    '- [Release Checklist](./docs/RELEASE_CHECKLIST.md) - Pre-release and deployment checklist',
    '',
    '## 👥 Team Onboarding',
    '',
    '### First Time Setup',
    '',
    '1. Clone the repository',
    '2. Run `npm install` to install dependencies',
    '3. Copy `.env.example` to `.env` and fill in the values',
    '4. Run `npm run dev` to start the development server',
    '5. Read the [AI Agent Guide](./docs/AGENT_GUIDE.md) to understand the project architecture and conventions',
    '',
    '### Development Workflow',
    '',
    '1. Create a new branch for your feature or bugfix',
    '2. Make your changes following the coding standards',
    '3. Run `npm run lint` to check for lint errors',
    '4. Run `npm test` to ensure all tests pass',
    '5. Run `npm run build` to verify TypeScript types',
    '6. Commit your changes using [Conventional Commits](https://www.conventionalcommits.org/)',
    '7. Push and open a Pull Request',
    '',
    '### CI/CD Pipeline',
    '',
    'This project uses GitHub Actions for continuous integration and deployment. On every push to `main` or `develop`, the pipeline will:',
    '',
    '- Install dependencies',
    '- Run lint checks',
    '- Run unit and integration tests',
    '- Build the project',
    '- Upload coverage reports',
    '',
    'Check `.github/workflows/ci-cd.yml` for the full pipeline configuration.',
    '',
    '## 🤝 Contributing',
    '',
    '1. Fork the repository',
    '2. Create your feature branch',
    '3. Commit your changes',
    '4. Push to the branch',
    '5. Open a Pull Request',
    '',
    '## 📄 License',
    '',
    'MIT License',
    '',
  ].join('\n');
}
