import type { ProjectConfig, SupportedLanguage } from '../types';

export function generateReleaseChecklist(config: ProjectConfig): string {
  const language: SupportedLanguage = config.cliLanguage ?? 'en';

  if (language === 'pt') {
    return [
      '# Checklist de Release',
      '',
      '## Pré-Release',
      '',
      '### Código',
      '',
      '- [ ] Todos os testes passando (`npm test`)',
      '- [ ] Coverage mínimo de 80% atingido',
      '- [ ] Lint sem erros (`npm run lint`)',
      '- [ ] Type check sem erros (`npm run build` ou `tsc --noEmit`)',
      '- [ ] Nenhuma variável não utilizada',
      '- [ ] Nenhum `console.log` deixado no código',
      '- [ ] Secrets e variáveis de ambiente configurados',
      '',
      '### QA',
      '',
      '- [ ] Testes E2E passando (`npm run test:e2e`)',
      '- [ ] Testes manuais em ambiente de staging',
      '- [ ] Validação de fluxos críticos (login, cadastro, principais features)',
      '- [ ] Testes em diferentes navegadores (Chrome, Firefox, Safari)',
      '- [ ] Testes responsivos (mobile, tablet, desktop)',
      '',
      '### Performance',
      '',
      '- [ ] Lighthouse score > 90 em Performance',
      '- [ ] Lighthouse score > 90 em Acessibilidade',
      '- [ ] Lighthouse score > 90 em Best Practices',
      '- [ ] Lighthouse score > 90 em SEO',
      '- [ ] Web Vitals dentro do aceitável:',
      '  - [ ] LCP < 2.5s',
      '  - [ ] FID < 100ms',
      '  - [ ] CLS < 0.1',
      '',
      '### Documentação',
      '',
      '- [ ] README atualizado com novas features',
      '- [ ] CHANGELOG.md atualizado',
      '- [ ] PRD revisado se houver mudanças de escopo',
      '- [ ] API.md atualizado (se aplicável)',
      '',
      '### SEO',
      '',
      '- [ ] Meta tags configuradas em todas as páginas',
      '- [ ] sitemap.xml gerado e atualizado',
      '- [ ] robots.txt configurado',
      '- [ ] Open Graph tags para redes sociais',
      '- [ ] Schema.org markup (se aplicável)',
      '',
      '### Acessibilidade',
      '',
      '- [ ] Navegação por teclado funcionando',
      '- [ ] Focus visível em todos os elementos interativos',
      '- [ ] Contraste de cores adequado',
      '- [ ] Alt text em imagens',
      '- [ ] Labels em formulários',
      '- [ ] ARIA attributes quando necessário',
      '',
      '## Deploy',
      '',
      '- [ ] Build de produção testado localmente',
      '- [ ] Variáveis de ambiente de produção configuradas',
      '- [ ] Database migrations aplicadas',
      '- [ ] Backup do banco de dados (se aplicável)',
      '- [ ] Rollback plan definido',
      '',
      '## Pós-Release',
      '',
      '- [ ] Monitorar logs de erro',
      '- [ ] Monitorar performance em produção',
      '- [ ] Coletar feedback dos usuários',
      '- [ ] Documentar lições aprendidas',
      '',
    ].join('\n');
  }

  if (language === 'es') {
    return [
      '# Checklist de Release',
      '',
      '## Pre-Release',
      '',
      '### Código',
      '',
      '- [ ] Todas las pruebas pasando (`npm test`)',
      '- [ ] Cobertura mínima del 80% alcanzada',
      '- [ ] Lint sin errores (`npm run lint`)',
      '- [ ] Type check sin errores (`npm run build` o `tsc --noEmit`)',
      '- [ ] Sin variables no utilizadas',
      '- [ ] Sin `console.log` en el código',
      '- [ ] Secrets y variables de entorno configurados',
      '',
      '### QA',
      '',
      '- [ ] Pruebas E2E pasando (`npm run test:e2e`)',
      '- [ ] Pruebas manuales en ambiente de staging',
      '- [ ] Validación de flujos críticos',
      '- [ ] Pruebas en diferentes navegadores',
      '- [ ] Pruebas responsivas',
      '',
      '### Performance',
      '',
      '- [ ] Lighthouse score > 90 en Performance',
      '- [ ] Lighthouse score > 90 en Accesibilidad',
      '- [ ] Lighthouse score > 90 en Best Practices',
      '- [ ] Lighthouse score > 90 en SEO',
      '- [ ] Web Vitals dentro de lo aceptable',
      '',
      '## Deploy',
      '',
      '- [ ] Build de producción probado localmente',
      '- [ ] Variables de entorno de producción configuradas',
      '- [ ] Database migrations aplicadas',
      '',
      '## Post-Release',
      '',
      '- [ ] Monitorear logs de error',
      '- [ ] Monitorear performance en producción',
      '',
    ].join('\n');
  }

  return [
    '# Release Checklist',
    '',
    '## Pre-Release',
    '',
    '### Code',
    '',
    '- [ ] All tests passing (`npm test`)',
    '- [ ] Minimum 80% coverage achieved',
    '- [ ] No lint errors (`npm run lint`)',
    '- [ ] No type errors (`npm run build` or `tsc --noEmit`)',
    '- [ ] No unused variables',
    '- [ ] No `console.log` left in code',
    '- [ ] Secrets and environment variables configured',
    '',
    '### QA',
    '',
    '- [ ] E2E tests passing (`npm run test:e2e`)',
    '- [ ] Manual testing in staging environment',
    '- [ ] Critical flows validation (login, signup, main features)',
    '- [ ] Cross-browser testing (Chrome, Firefox, Safari)',
    '- [ ] Responsive testing (mobile, tablet, desktop)',
    '',
    '### Performance',
    '',
    '- [ ] Lighthouse score > 90 in Performance',
    '- [ ] Lighthouse score > 90 in Accessibility',
    '- [ ] Lighthouse score > 90 in Best Practices',
    '- [ ] Lighthouse score > 90 in SEO',
    '- [ ] Web Vitals within acceptable range:',
    '  - [ ] LCP < 2.5s',
    '  - [ ] FID < 100ms',
    '  - [ ] CLS < 0.1',
    '',
    '### Documentation',
    '',
    '- [ ] README updated with new features',
    '- [ ] CHANGELOG.md updated',
    '- [ ] PRD reviewed if scope changes',
    '- [ ] API.md updated (if applicable)',
    '',
    '### SEO',
    '',
    '- [ ] Meta tags configured on all pages',
    '- [ ] sitemap.xml generated and updated',
    '- [ ] robots.txt configured',
    '- [ ] Open Graph tags for social media',
    '- [ ] Schema.org markup (if applicable)',
    '',
    '### Accessibility',
    '',
    '- [ ] Keyboard navigation working',
    '- [ ] Visible focus on all interactive elements',
    '- [ ] Adequate color contrast',
    '- [ ] Alt text on images',
    '- [ ] Labels on forms',
    '- [ ] ARIA attributes when needed',
    '',
    '## Deploy',
    '',
    '- [ ] Production build tested locally',
    '- [ ] Production environment variables configured',
    '- [ ] Database migrations applied',
    '- [ ] Database backup (if applicable)',
    '- [ ] Rollback plan defined',
    '',
    '## Post-Release',
    '',
    '- [ ] Monitor error logs',
    '- [ ] Monitor production performance',
    '- [ ] Collect user feedback',
    '- [ ] Document lessons learned',
    '',
  ].join('\n');
}
