export function generateApiService(): string {
  return [
    "import axios from 'axios';",
    '',
    "const API_BASE_URL = import.meta.env.VITE_API_URL ?? 'http://localhost:3000/api';",
    '',
    'export const api = axios.create({',
    '  baseURL: API_BASE_URL,',
    '  withCredentials: true,',
    '});',
    '',
  ].join('\n');
}

export function generateAuthService(): string {
  return [
    "import type { AxiosResponse } from 'axios';",
    "import { api } from './api';",
    '',
    'interface AuthResponse {',
    '  token: string;',
    '  user: {',
    '    id: string;',
    '    email: string;',
    '    name: string;',
    '  };',
    '}',
    '',
    'export const authService = {',
    '  async register(name: string, email: string, password: string): Promise<AuthResponse> {',
    '    const response: AxiosResponse<AuthResponse> = await api.post("/auth/register", {',
    '      name,',
    '      email,',
    '      password,',
    '    });',
    '    return response.data;',
    '  },',
    '',
    '  async login(email: string, password: string): Promise<AuthResponse> {',
    '    const response: AxiosResponse<AuthResponse> = await api.post("/auth/login", {',
    '      email,',
    '      password,',
    '    });',
    '    return response.data;',
    '  },',
    '',
    '  async getCurrentUser(): Promise<AuthResponse["user"]> {',
    '    const response: AxiosResponse<AuthResponse["user"]> = await api.get("/auth/me");',
    '    return response.data;',
    '  },',
    '',
    '  async logout(): Promise<void> {',
    '    await api.post("/auth/logout");',
    '  },',
    '};',
    '',
  ].join('\n');
}

export function generateMainFile(): string {
  return [
    "import React from 'react';",
    "import ReactDOM from 'react-dom/client';",
    "import App from './App';",
    "import './styles/globals.css';",
    '',
    "ReactDOM.createRoot(document.getElementById('root')!).render(",
    '  <React.StrictMode>',
    '    <App />',
    '  </React.StrictMode>',
    ');',
    '',
  ].join('\n');
}

export function generateZustandStore(): string {
  return [
    "import { create } from 'zustand';",
    '',
    'interface IAppState {',
    '  readonly isAuthenticated: boolean;',
    '  readonly userName: string | null;',
    '}',
    '',
    'interface IAppActions {',
    '  readonly login: (userName: string) => void;',
    '  readonly logout: () => void;',
    '}',
    '',
    'type IStoreState = IAppState & IAppActions;',
    '',
    'export const useAppStore = create<IStoreState>((set) => ({',
    '  isAuthenticated: false,',
    '  userName: null,',
    '  login: (userName: string): void => {',
    '    set(() => ({',
    '      isAuthenticated: true,',
    '      userName,',
    '    }));',
    '  },',
    '  logout: (): void => {',
    '    set(() => ({',
    '      isAuthenticated: false,',
    '      userName: null,',
    '    }));',
    '  },',
    '}));',
    '',
  ].join('\n');
}

export function generateReduxStore(): string {
  return [
    "import { configureStore } from '@reduxjs/toolkit';",
    '',
    'export interface IAppState {',
    '  readonly isAuthenticated: boolean;',
    '}',
    '',
    'interface IAction {',
    '  readonly type: string;',
    '}',
    '',
    'const initialState: IAppState = {',
    '  isAuthenticated: false,',
    '};',
    '',
    'const rootReducer = (state: IAppState = initialState, action: IAction): IAppState => {',
    '  switch (action.type) {',
    '    default:',
    '      return state;',
    '  }',
    '};',
    '',
    'export const store = configureStore({',
    '  reducer: rootReducer,',
    '});',
    '',
    'export type IRootState = ReturnType<typeof store.getState>;',
    'export type IAppDispatch = typeof store.dispatch;',
    '',
  ].join('\n');
}

export function generateReduxHooks(): string {
  return [
    "import { useDispatch, useSelector, type TypedUseSelectorHook } from 'react-redux';",
    "import type { IAppDispatch, IRootState } from './index';",
    '',
    'export const useAppDispatch = (): IAppDispatch => useDispatch<IAppDispatch>();',
    'export const useAppSelector: TypedUseSelectorHook<IRootState> = useSelector;',
    '',
  ].join('\n');
}
