export function generateBackendIndexFile(): string {
  return [
    "import app from './app';",
    "import { logger } from './utils/logger';",
    '',
    'const DEFAULT_PORT = 3000;',
    '',
    'const portFromEnv = process.env.PORT;',
    '',
    'const port = portFromEnv !== undefined ? Number(portFromEnv) || DEFAULT_PORT : DEFAULT_PORT;',
    '',
    'app.listen(port, () => {',
    '  logger.info(`Server running on port ${port}`);',
    "  logger.info(`Environment: ${process.env.NODE_ENV ?? 'development'}`);",
    '});',
    '',
  ].join('\n');
}

export function generateBackendAppFile(): string {
  return [
    "import express from 'express';",
    "import cors from 'cors';",
    "import { routes } from './routes';",
    "import { errorMiddleware } from './middlewares/error.middleware';",
    "import { logger } from './utils/logger';",
    "import { config } from './config';",
    '',
    'const app = express();',
    '',
    'app.use(cors(config.cors));',
    'app.use(express.json());',
    'app.use(express.urlencoded({ extended: true }));',
    '',
    'app.use((req, res, next) => {',
    '  logger.info(`${req.method} ${req.path}`);',
    '  next();',
    '});',
    '',
    "app.use('/api', routes);",
    '',
    "app.get('/health', (req, res) => {",
    "  res.json({ status: 'ok', timestamp: new Date().toISOString() });",
    '});',
    '',
    'app.use(errorMiddleware);',
    '',
    'export default app;',
    '',
  ].join('\n');
}

export function generateBackendConfigFile(): string {
  return [
    "import dotenv from 'dotenv';",
    '',
    'dotenv.config();',
    '',
    'const DEFAULT_PORT = 3000;',
    '',
    'const parseAllowedOrigins = (value: string | undefined): string[] | undefined => {',
    '  if (value === undefined) {',
    '    return undefined;',
    '  }',
    '',
    '  return value',
    "    .split(',')",
    '    .map((origin) => origin.trim())',
    '    .filter((origin) => origin.length > 0);',
    '};',
    '',
    'const getJwtSecret = (): string => {',
    '  const secret = process.env.JWT_SECRET;',
    '',
    '  if (secret === undefined) {',
    "    throw new Error('JWT_SECRET environment variable must be set for security reasons.');",
    '  }',
    '',
    '  return secret;',
    '};',
    '',
    'const corsAllowedOrigins = parseAllowedOrigins(process.env.CORS_ALLOWED_ORIGINS);',
    '',
    'export const config = {',
    '  port: Number(process.env.PORT) || DEFAULT_PORT,',
    "  nodeEnv: process.env.NODE_ENV ?? 'development',",
    '  jwt: {',
    '    secret: getJwtSecret(),',
    "    expiresIn: process.env.JWT_EXPIRES_IN ?? '7d',",
    '  },',
    '  database: {',
    "    url: process.env.DATABASE_URL ?? '',",
    '  },',
    '  cors: {',
    '    origin: corsAllowedOrigins ?? "*",',
    '    credentials: true,',
    '  },',
    '};',
    '',
  ].join('\n');
}
