export function generateRoutesIndexFile(): string {
  return [
    "export { authRoutes } from './auth.routes';",
    "export { userRoutes } from './user.routes';",
    '',
  ].join('\n');
}

export function generateAuthRoutesFile(): string {
  return [
    "import { Router } from 'express';",
    "import { authController } from '../controllers/auth.controller';",
    '',
    'export const authRoutes = Router();',
    '',
    "authRoutes.post('/register', authController.register);",
    "authRoutes.post('/login', authController.login);",
    "authRoutes.post('/logout', authController.logout);",
    "authRoutes.get('/me', authController.getCurrentUser);",
    '',
  ].join('\n');
}

export function generateUserRoutesFile(): string {
  return [
    "import { Router } from 'express';",
    "import { userController } from '../controllers/user.controller';",
    "import { authMiddleware } from '../middlewares/auth.middleware';",
    '',
    'export const userRoutes = Router();',
    'userRoutes.use(authMiddleware);',
    '',
    "userRoutes.get('/profile', userController.getProfile);",
    "userRoutes.put('/profile', userController.updateProfile);",
    '',
  ].join('\n');
}

export function generateAuthControllerFile(): string {
  return [
    "import type { AuthRequest } from '../middlewares/auth.middleware';",
    "import type { NextFunction, Response } from 'express';",
    "import { authService } from '../services/auth.service';",
    '',
    'export const authController = {',
    '  async register(req: AuthRequest, res: Response, next: NextFunction) {',
    '    try {',
    '      const { name, email, password } = req.body;',
    '      const result = await authService.register(name, email, password);',
    '      res.status(201).json(result);',
    '    } catch (error) {',
    '      next(error);',
    '    }',
    '  },',
    '',
    '  async login(req: AuthRequest, res: Response, next: NextFunction) {',
    '    try {',
    '      const { email, password } = req.body;',
    '      const result = await authService.login(email, password);',
    '      res.json(result);',
    '    } catch (error) {',
    '      next(error);',
    '    }',
    '  },',
    '',
    '  async logout(req: AuthRequest, res: Response, next: NextFunction) {',
    '    try {',
    '      const token = req.headers.authorization?.split(" ")[1] ?? "";',
    '      await authService.logout(token);',
    "      res.json({ message: 'Logged out successfully' });",
    '    } catch (error) {',
    '      next(error);',
    '    }',
    '  },',
    '',
    '  async getCurrentUser(req: AuthRequest, res: Response, next: NextFunction) {',
    '    try {',
    '      const userId = req.user?.userId;',
    '      if (userId === undefined) {',
    "        res.status(401).json({ message: 'Unauthorized' });",
    '        return;',
    '      }',
    '      const user = await authService.getUserById(userId);',
    '      res.json(user);',
    '    } catch (error) {',
    '      next(error);',
    '    }',
    '  },',
    '};',
    '',
  ].join('\n');
}

export function generateUserControllerFile(): string {
  return [
    "import type { AuthRequest } from '../middlewares/auth.middleware';",
    "import type { NextFunction, Response } from 'express';",
    "import { userService } from '../services/user.service';",
    '',
    'export const userController = {',
    '  async getProfile(req: AuthRequest, res: Response, next: NextFunction) {',
    '    try {',
    '      const userId = req.user?.userId;',
    '      if (userId === undefined) {',
    "        res.status(401).json({ message: 'Unauthorized' });",
    '        return;',
    '      }',
    '      const user = await userService.getUserById(userId);',
    '      res.json(user);',
    '    } catch (error) {',
    '      next(error);',
    '    }',
    '  },',
    '',
    '  async updateProfile(req: AuthRequest, res: Response, next: NextFunction) {',
    '    try {',
    '      const userId = req.user?.userId;',
    '      if (userId === undefined) {',
    "        res.status(401).json({ message: 'Unauthorized' });",
    '        return;',
    '      }',
    '      const updates = req.body as { name?: string; email?: string };',
    '      const user = await userService.updateUser(userId, updates);',
    '      res.json(user);',
    '    } catch (error) {',
    '      next(error);',
    '    }',
    '  },',
    '};',
    '',
  ].join('\n');
}
