export function generateAuthServiceBackend(): string {
  const lines: string[] = [
    "import bcrypt from 'bcrypt';",
    "import jwt from 'jsonwebtoken';",
    "import { Prisma } from '@prisma/client';",
    "import { prisma } from '../database';",
    "import { config } from '../config';",
    "import { HttpError } from '../utils/httpError';",
    '',
    'const handlePrismaError = (error: unknown): never => {',
    '  if (error instanceof Prisma.PrismaClientKnownRequestError) {',
    "    if (error.code === 'P2002') {",
    "      throw new HttpError(409, 'Email already registered');",
    '    }',
    '  }',
    '',
    '  if (error instanceof Error) {',
    '    throw new HttpError(500, error.message);',
    '  }',
    '',
    "  throw new HttpError(500, 'Unexpected database error');",
    '};',
    '',
    'export const authService = {',
    '  async register(name: string, email: string, password: string) {',
    '    try {',
    '      const existingUser = await prisma.user.findUnique({ where: { email } });',
    '      ',
    '      if (existingUser) {',
    "        throw new HttpError(409, 'Email already registered');",
    '      }',
    '  ',
    '      const hashedPassword = await bcrypt.hash(password, 12);',
    '      ',
    '      const user = await prisma.user.create({',
    '        data: { name, email, password: hashedPassword },',
    '      });',
    '  ',
    '      const token = jwt.sign({ userId: user.id, email: user.email }, config.jwt.secret, {',
    '        expiresIn: config.jwt.expiresIn,',
    '      });',
    '  ',
    '      return {',
    '        token,',
    '        user: { id: user.id, email: user.email, name: user.name },',
    '      };',
    '    } catch (error) {',
    '      handlePrismaError(error);',
    '    }',
    '  },',
    '',
    '  async login(email: string, password: string) {',
    '    try {',
    '      const user = await prisma.user.findUnique({ where: { email } });',
    '      ',
    '      if (!user) {',
    "        throw new HttpError(401, 'Invalid credentials');",
    '      }',
    '  ',
    '      const isPasswordValid = await bcrypt.compare(password, user.password);',
    '      ',
    '      if (!isPasswordValid) {',
    "        throw new HttpError(401, 'Invalid credentials');",
    '      }',
    '  ',
    '      const token = jwt.sign({ userId: user.id, email: user.email }, config.jwt.secret, {',
    '        expiresIn: config.jwt.expiresIn,',
    '      });',
    '  ',
    '      return {',
    '        token,',
    '        user: { id: user.id, email: user.email, name: user.name },',
    '      };',
    '    } catch (error) {',
    '      handlePrismaError(error);',
    '    }',
    '  },',
    '',
    '  async logout(token: string) {',
    '    if (!token) {',
    '      return;',
    '    }',
    '    // In a real system we would implement token blacklist or rotation',
    '  },',
    '',
    '  async getUserById(id: string) {',
    '    try {',
    '      const user = await prisma.user.findUnique({',
    '        where: { id },',
    '        select: { id: true, email: true, name: true, createdAt: true },',
    '      });',
    '',
    '      if (!user) {',
    "        throw new HttpError(404, 'User not found');",
    '      }',
    '',
    '      return user;',
    '    } catch (error) {',
    '      handlePrismaError(error);',
    '    }',
    '  },',
    '};',
    '',
  ];

  return lines.join('\n');
}

export function generateUserServiceBackend(): string {
  return [
    "import { Prisma } from '@prisma/client';",
    "import { prisma } from '../database';",
    "import { HttpError } from '../utils/httpError';",
    '',
    'const handlePrismaError = (error: unknown): never => {',
    '  if (error instanceof Prisma.PrismaClientKnownRequestError) {',
    "    if (error.code === 'P2025') {",
    "      throw new HttpError(404, 'User not found');",
    '    }',
    '  }',
    '',
    '  if (error instanceof Error) {',
    '    throw new HttpError(500, error.message);',
    '  }',
    '',
    "  throw new HttpError(500, 'Unexpected database error');",
    '};',
    '',
    'export const userService = {',
    '  async getUserById(id: string) {',
    '    try {',
    '      const user = await prisma.user.findUnique({',
    '        where: { id },',
    '        select: { id: true, email: true, name: true, createdAt: true },',
    '      });',
    '',
    '      if (!user) {',
    "        throw new HttpError(404, 'User not found');",
    '      }',
    '',
    '      return user;',
    '    } catch (error) {',
    '      handlePrismaError(error);',
    '    }',
    '  },',
    '',
    '  async updateUser(id: string, updates: { name?: string; email?: string }) {',
    '    try {',
    '      const user = await prisma.user.update({',
    '        where: { id },',
    '        data: updates,',
    '        select: { id: true, email: true, name: true, updatedAt: true },',
    '      });',
    '',
    '      return user;',
    '    } catch (error) {',
    '      handlePrismaError(error);',
    '    }',
    '  },',
    '};',
    '',
  ].join('\n');
}

export function generateAuthMiddlewareFile(): string {
  return [
    "import type { NextFunction, Request, Response } from 'express';",
    "import jwt from 'jsonwebtoken';",
    "import { config } from '../config';",
    '',
    'export interface AuthRequest extends Request {',
    '  user?: { userId: string; email: string };',
    '}',
    '',
    'export const authMiddleware = (req: AuthRequest, res: Response, next: NextFunction) => {',
    '  const authHeader = req.headers.authorization;',
    '  ',
    "  if (authHeader === undefined || !authHeader.startsWith('Bearer ')) {",
    "    res.status(401).json({ message: 'Authorization token required' });",
    '    return;',
    '  }',
    '',
    "  const token = authHeader.split(' ')[1];",
    '',
    '  try {',
    '    const decoded = jwt.verify(token, config.jwt.secret) as { userId: string; email: string };',
    '    req.user = decoded;',
    '    next();',
    '  } catch (error) {',
    "    res.status(401).json({ message: 'Invalid or expired token' });",
    '  }',
    '};',
    '',
  ].join('\n');
}

export function generateErrorMiddlewareFile(): string {
  return [
    "import type { NextFunction, Request, Response } from 'express';",
    "import { logger } from '../utils/logger';",
    "import { HttpError } from '../utils/httpError';",
    '',
    'export const errorMiddleware = (',
    '  error: Error,',
    '  req: Request,',
    '  res: Response,',
    '  next: NextFunction',
    ') => {',
    '  logger.error(`Error: ${error.message}`, { stack: error.stack });',
    '',
    '  const statusCode = error instanceof HttpError ? error.statusCode : 500;',
    '',
    '  res.status(statusCode).json({',
    '    error: {',
    "      message: process.env.NODE_ENV === 'production' ? 'Internal server error' : error.message,",
    '      statusCode,',
    '    },',
    '  });',
    '};',
    '',
  ].join('\n');
}

export function generateLoggerFile(): string {
  return [
    "import winston from 'winston';",
    '',
    'export const logger = winston.createLogger({',
    "  level: process.env.LOG_LEVEL ?? 'info',",
    '  format: winston.format.combine(',
    '    winston.format.timestamp(),',
    '    winston.format.json()',
    '  ),',
    '  transports: [',
    "    new winston.transports.File({ filename: 'logs/error.log', level: 'error' }),",
    "    new winston.transports.File({ filename: 'logs/combined.log' }),",
    '  ],',
    '});',
    '',
    "if (process.env.NODE_ENV !== 'production') {",
    '  logger.add(',
    '    new winston.transports.Console({',
    '      format: winston.format.simple(),',
    '    })',
    '  );',
    '}',
    '',
  ].join('\n');
}

export function generateHttpErrorFile(): string {
  return [
    'export class HttpError extends Error {',
    '  constructor(public statusCode: number, message: string) {',
    '    super(message);',
    "    this.name = 'HttpError';",
    '  }',
    '}',
    '',
  ].join('\n');
}
