export function generateUseAuthHook(): string {
  return [
    "import { useContext } from 'react';",
    "import { AuthContext } from '@/context/AuthContext';",
    '',
    'export const useAuth = () => {',
    '  const context = useContext(AuthContext);',
    '  ',
    '  if (!context) {',
    "    throw new Error('useAuth must be used within an AuthProvider');",
    '  }',
    '  ',
    '  return context;',
    '};',
    '',
  ].join('\n');
}

export function generateUseThemeHook(): string {
  return [
    "import { useContext } from 'react';",
    "import { ThemeContext } from '@/context/ThemeContext';",
    '',
    'export const useTheme = () => {',
    '  const context = useContext(ThemeContext);',
    '  ',
    '  if (!context) {',
    "    throw new Error('useTheme must be used within a ThemeProvider');",
    '  }',
    '  ',
    '  return context;',
    '};',
    '',
  ].join('\n');
}

export function generateAuthContext(): string {
  return [
    "import React, { createContext, useState, useEffect, type ReactNode } from 'react';",
    "import { authService } from '@/services/auth';",
    '',
    'export interface User {',
    '  id: string;',
    '  email: string;',
    '  name: string;',
    '}',
    '',
    'export interface AuthContextType {',
    '  user: User | null;',
    '  isLoading: boolean;',
    '  isAuthenticated: boolean;',
    '  login: (email: string, password: string) => Promise<void>;',
    '  register: (name: string, email: string, password: string) => Promise<void>;',
    '  logout: () => Promise<void>;',
    '}',
    '',
    'export const AuthContext = createContext<AuthContextType | undefined>(undefined);',
    '',
    'interface AuthProviderProps {',
    '  children: ReactNode;',
    '}',
    '',
    'export const AuthProvider: React.FC<AuthProviderProps> = ({ children }) => {',
    '  const [user, setUser] = useState<User | null>(null);',
    '  const [isLoading, setIsLoading] = useState(true);',
    '',
    '  useEffect(() => {',
    "    const token = localStorage.getItem('token');",
    '    if (token) {',
    '      authService',
    '        .getCurrentUser()',
    '        .then(setUser)',
    "        .catch(() => localStorage.removeItem('token'))",
    '        .finally(() => setIsLoading(false));',
    '    } else {',
    '      setIsLoading(false);',
    '    }',
    '  }, []);',
    '',
    '  const login = async (email: string, password: string) => {',
    '    const response = await authService.login(email, password);',
    "    localStorage.setItem('token', response.token);",
    '    setUser(response.user);',
    '  };',
    '',
    '  const register = async (name: string, email: string, password: string) => {',
    '    const response = await authService.register(name, email, password);',
    "    localStorage.setItem('token', response.token);",
    '    setUser(response.user);',
    '  };',
    '',
    '  const logout = async () => {',
    '    await authService.logout();',
    "    localStorage.removeItem('token');",
    '    setUser(null);',
    '  };',
    '',
    '  return (',
    '    <AuthContext.Provider',
    '      value={{ user, isLoading, isAuthenticated: user !== null, login, register, logout }}',
    '    >',
    '      {children}',
    '    </AuthContext.Provider>',
    '  );',
    '};',
    '',
  ].join('\n');
}

export function generateThemeContext(): string {
  return [
    "import React, { createContext, useState, useEffect, type ReactNode } from 'react';",
    '',
    'export type Theme = "light" | "dark";',
    '',
    'export interface ThemeContextType {',
    '  theme: Theme;',
    '  toggleTheme: () => void;',
    '}',
    '',
    'export const ThemeContext = createContext<ThemeContextType | undefined>(undefined);',
    '',
    'interface ThemeProviderProps {',
    '  children: ReactNode;',
    '}',
    '',
    'export const ThemeProvider: React.FC<ThemeProviderProps> = ({ children }) => {',
    "  const [theme, setTheme] = useState<Theme>('light');",
    '',
    '  useEffect(() => {',
    '    const storedTheme = window.localStorage.getItem("theme");',
    "    if (storedTheme === 'light' || storedTheme === 'dark') {",
    '      setTheme(storedTheme);',
    '    }',
    '  }, []);',
    '',
    '  useEffect(() => {',
    '    window.localStorage.setItem("theme", theme);',
    '    document.documentElement.dataset.theme = theme;',
    '  }, [theme]);',
    '',
    '  const toggleTheme = () => {',
    "    setTheme((current) => (current === 'light' ? 'dark' : 'light'));",
    '  };',
    '',
    '  return (',
    '    <ThemeContext.Provider value={{ theme, toggleTheme }}>',
    '      {children}',
    '    </ThemeContext.Provider>',
    '  );',
    '};',
    '',
  ].join('\n');
}
