import type { SupportedLanguage } from '../../types';

interface IDesignSystemLocaleHeadings {
  readonly title: string;
  readonly colors: string;
  readonly semanticColors: string;
  readonly typography: string;
  readonly fontFamilies: string;
  readonly fontSizes: string;
  readonly headings: string;
  readonly spacing: string;
  readonly breakpoints: string;
  readonly components: string;
  readonly designGuidelines: string;
  readonly principles: string;
  readonly accessibility: string;
  readonly responsiveDesign: string;
  readonly motion: string;
}

interface IDesignSystemLocaleLabels {
  readonly usage: string;
  readonly token: string;
  readonly value: string;
  readonly name: string;
  readonly cssVariable: string;
  readonly css: string;
  readonly level: string;
  readonly size: string;
  readonly weight: string;
  readonly lineHeight: string;
  readonly description: string;
  readonly examples: string;
  readonly guideline: string;
  readonly example: string;
  readonly type: string;
  readonly duration: string;
  readonly easing: string;
  readonly generatedBy: string;
  readonly colorSystemDescription: string;
}

export interface IDesignSystemLocaleTexts {
  readonly headings: IDesignSystemLocaleHeadings;
  readonly labels: IDesignSystemLocaleLabels;
}

export const DESIGN_SYSTEM_LOCALE_TEXTS: Record<SupportedLanguage, IDesignSystemLocaleTexts> = {
  en: {
    headings: {
      title: 'Design System',
      colors: 'Colors',
      semanticColors: 'Semantic Colors',
      typography: 'Typography',
      fontFamilies: 'Font Families',
      fontSizes: 'Font Sizes',
      headings: 'Headings',
      spacing: 'Spacing',
      breakpoints: 'Breakpoints',
      components: 'Components',
      designGuidelines: 'Design Guidelines',
      principles: 'Principles',
      accessibility: 'Accessibility',
      responsiveDesign: 'Responsive Design',
      motion: 'Motion',
    },
    labels: {
      usage: 'Usage',
      token: 'Token',
      value: 'Value',
      name: 'Name',
      cssVariable: 'CSS Variable',
      css: 'CSS',
      level: 'Level',
      size: 'Size',
      weight: 'Weight',
      lineHeight: 'Line Height',
      description: 'Description',
      examples: 'Examples',
      guideline: 'Guideline',
      example: 'Example',
      type: 'Type',
      duration: 'Duration',
      easing: 'Easing',
      generatedBy: 'Design System automatically generated by the sparkseed CLI',
      colorSystemDescription:
        'The color system is based on a semantic palette that makes maintenance easier and ensures visual consistency.',
    },
  },
  pt: {
    headings: {
      title: 'Design System',
      colors: 'Cores',
      semanticColors: 'Cores Semânticas',
      typography: 'Tipografia',
      fontFamilies: 'Famílias de Fonte',
      fontSizes: 'Tamanhos de Fonte',
      headings: 'Títulos',
      spacing: 'Espaçamento',
      breakpoints: 'Breakpoints',
      components: 'Componentes',
      designGuidelines: 'Diretrizes de Design',
      principles: 'Princípios',
      accessibility: 'Acessibilidade',
      responsiveDesign: 'Design Responsivo',
      motion: 'Movimento',
    },
    labels: {
      usage: 'Uso',
      token: 'Token',
      value: 'Valor',
      name: 'Nome',
      cssVariable: 'Variável CSS',
      css: 'CSS',
      level: 'Nível',
      size: 'Tamanho',
      weight: 'Peso',
      lineHeight: 'Altura da Linha',
      description: 'Descrição',
      examples: 'Exemplos',
      guideline: 'Diretriz',
      example: 'Exemplo',
      type: 'Tipo',
      duration: 'Duração',
      easing: 'Easing',
      generatedBy: 'Design System gerado automaticamente pela CLI sparkseed',
      colorSystemDescription:
        'O sistema de cores é baseado em uma paleta semântica que facilita a manutenção e garante consistência visual.',
    },
  },
  es: {
    headings: {
      title: 'Design System',
      colors: 'Colores',
      semanticColors: 'Colores Semánticos',
      typography: 'Tipografía',
      fontFamilies: 'Familias Tipográficas',
      fontSizes: 'Tamaños de Fuente',
      headings: 'Encabezados',
      spacing: 'Espaciado',
      breakpoints: 'Breakpoints',
      components: 'Componentes',
      designGuidelines: 'Guías de Diseño',
      principles: 'Principios',
      accessibility: 'Accesibilidad',
      responsiveDesign: 'Diseño Responsivo',
      motion: 'Movimiento',
    },
    labels: {
      usage: 'Uso',
      token: 'Token',
      value: 'Valor',
      name: 'Nombre',
      cssVariable: 'Variable CSS',
      css: 'CSS',
      level: 'Nivel',
      size: 'Tamaño',
      weight: 'Peso',
      lineHeight: 'Altura de Línea',
      description: 'Descripción',
      examples: 'Ejemplos',
      guideline: 'Guía',
      example: 'Ejemplo',
      type: 'Tipo',
      duration: 'Duración',
      easing: 'Easing',
      generatedBy: 'Design System generado automáticamente por la CLI sparkseed',
      colorSystemDescription:
        'El sistema de color se basa en una paleta semántica que facilita el mantenimiento y garantiza la consistencia visual.',
    },
  },
};
