import { PRD, SupportedLanguage } from '../../types';

interface IPrdLocaleHeadings {
  readonly title: string;
  readonly objectives: string;
  readonly targetAudience: string;
  readonly userPersonas: string;
  readonly userStories: string;
  readonly functionalRequirements: string;
  readonly nonFunctionalRequirements: string;
  readonly technicalStack: string;
  readonly milestones: string;
  readonly successMetrics: string;
}

interface IPrdLocaleLabels {
  readonly role: string;
  readonly goals: string;
  readonly painPoints: string;
  readonly behaviors: string;
  readonly description: string;
  readonly acceptanceCriteria: string;
  readonly priority: string;
  readonly frontend: string;
  readonly backend: string;
  readonly database: string;
  readonly hosting: string;
  readonly tooling: string;
  readonly generatedBy: string;
}

interface IPrdLocalePriorities {
  readonly high: string;
  readonly medium: string;
  readonly low: string;
}

interface IPrdLocaleTexts {
  readonly headings: IPrdLocaleHeadings;
  readonly labels: IPrdLocaleLabels;
  readonly priorities: IPrdLocalePriorities;
}

const PRD_LOCALE_TEXTS: Record<SupportedLanguage, IPrdLocaleTexts> = {
  en: {
    headings: {
      title: 'Product Requirements Document (PRD)',
      objectives: 'Objectives',
      targetAudience: 'Target Audience',
      userPersonas: 'User Personas',
      userStories: 'User Stories',
      functionalRequirements: 'Functional Requirements',
      nonFunctionalRequirements: 'Non-Functional Requirements',
      technicalStack: 'Technical Stack',
      milestones: 'Milestones',
      successMetrics: 'Success Metrics',
    },
    labels: {
      role: 'Role',
      goals: 'Goals',
      painPoints: 'Pain Points',
      behaviors: 'Behaviors',
      description: 'Description',
      acceptanceCriteria: 'Acceptance Criteria',
      priority: 'Priority',
      frontend: 'Frontend',
      backend: 'Backend',
      database: 'Database',
      hosting: 'Hosting',
      tooling: 'Tooling',
      generatedBy: 'Document automatically generated by the sparkseed CLI',
    },
    priorities: {
      high: '🔴 High',
      medium: '🟡 Medium',
      low: '🟢 Low',
    },
  },
  pt: {
    headings: {
      title: 'Documento de Requisitos de Produto (PRD)',
      objectives: 'Objetivos',
      targetAudience: 'Público-alvo',
      userPersonas: 'Personas de Usuário',
      userStories: 'Histórias de Usuário',
      functionalRequirements: 'Requisitos Funcionais',
      nonFunctionalRequirements: 'Requisitos Não Funcionais',
      technicalStack: 'Stack Técnica',
      milestones: 'Marcos',
      successMetrics: 'Métricas de Sucesso',
    },
    labels: {
      role: 'Papel',
      goals: 'Objetivos',
      painPoints: 'Dores',
      behaviors: 'Comportamentos',
      description: 'Descrição',
      acceptanceCriteria: 'Critérios de Aceite',
      priority: 'Prioridade',
      frontend: 'Frontend',
      backend: 'Backend',
      database: 'Banco de Dados',
      hosting: 'Hospedagem',
      tooling: 'Ferramentas',
      generatedBy: 'Documento gerado automaticamente pela CLI sparkseed',
    },
    priorities: {
      high: '🔴 Alta',
      medium: '🟡 Média',
      low: '🟢 Baixa',
    },
  },
  es: {
    headings: {
      title: 'Documento de Requisitos de Producto (PRD)',
      objectives: 'Objetivos',
      targetAudience: 'Público objetivo',
      userPersonas: 'Personas de Usuario',
      userStories: 'Historias de Usuario',
      functionalRequirements: 'Requisitos Funcionales',
      nonFunctionalRequirements: 'Requisitos No Funcionales',
      technicalStack: 'Stack Técnico',
      milestones: 'Hitos',
      successMetrics: 'Métricas de Éxito',
    },
    labels: {
      role: 'Rol',
      goals: 'Objetivos',
      painPoints: 'Puntos de dolor',
      behaviors: 'Comportamientos',
      description: 'Descripción',
      acceptanceCriteria: 'Criterios de Aceptación',
      priority: 'Prioridad',
      frontend: 'Frontend',
      backend: 'Backend',
      database: 'Base de Datos',
      hosting: 'Hosting',
      tooling: 'Herramientas',
      generatedBy: 'Documento generado automáticamente por la CLI sparkseed',
    },
    priorities: {
      high: '🔴 Alta',
      medium: '🟡 Media',
      low: '🟢 Baja',
    },
  },
};

export function formatPRD(prd: PRD, language?: SupportedLanguage): string {
  const texts = getPrdLocaleTexts(language);

  let markdown = `# 📋 ${texts.headings.title}\n\n`;
  markdown += `## ${prd.overview}\n\n`;

  markdown += `## 🎯 ${texts.headings.objectives}\n\n`;
  prd.objectives.forEach((obj, index) => {
    markdown += `${index + 1}. ${obj}\n`;
  });
  markdown += `\n`;

  markdown += `## 👥 ${texts.headings.targetAudience}\n\n`;
  markdown += `${prd.targetAudience}\n\n`;

  markdown += `## 🎭 ${texts.headings.userPersonas}\n\n`;
  prd.userPersonas.forEach((persona) => {
    markdown += `### ${persona.name}\n`;
    markdown += `**${texts.labels.role}:** ${persona.role}\n\n`;
    markdown += `**${texts.labels.goals}:**\n`;
    persona.goals.forEach((goal) => {
      markdown += `- ${goal}\n`;
    });
    markdown += `\n**${texts.labels.painPoints}:**\n`;
    persona.painPoints.forEach((pain) => {
      markdown += `- ${pain}\n`;
    });
    markdown += `\n**${texts.labels.behaviors}:**\n`;
    persona.behaviors.forEach((behavior) => {
      markdown += `- ${behavior}\n`;
    });
    markdown += `\n---\n\n`;
  });

  markdown += `## 📖 ${texts.headings.userStories}\n\n`;
  prd.userStories.forEach((story) => {
    markdown += `### ${story.id} - ${story.title}\n`;
    markdown += `**${texts.labels.description}:** ${story.description}\n\n`;
    markdown += `**${texts.labels.acceptanceCriteria}:**\n`;
    story.acceptanceCriteria.forEach((criteria) => {
      markdown += `- [ ] ${criteria}\n`;
    });
    const priorityText =
      story.priority === 'high'
        ? texts.priorities.high
        : story.priority === 'medium'
          ? texts.priorities.medium
          : texts.priorities.low;
    markdown += `**${texts.labels.priority}:** ${priorityText}\n\n`;
  });

  markdown += `## ⚙️ ${texts.headings.functionalRequirements}\n\n`;
  prd.functionalRequirements.forEach((req) => {
    markdown += `### ${req.id} - ${req.title}\n`;
    markdown += `${req.description}\n\n`;
    const priorityText =
      req.priority === 'high'
        ? texts.priorities.high
        : req.priority === 'medium'
          ? texts.priorities.medium
          : texts.priorities.low;
    markdown += `**${texts.labels.priority}:** ${priorityText}\n\n`;
  });

  markdown += `## 📐 ${texts.headings.nonFunctionalRequirements}\n\n`;
  prd.nonFunctionalRequirements.forEach((req, index) => {
    markdown += `${index + 1}. ${req}\n`;
  });
  markdown += `\n`;

  markdown += `## 🛠️ ${texts.headings.technicalStack}\n\n`;
  markdown += `### ${texts.labels.frontend}\n`;
  prd.technicalStack.frontend.forEach((tech) => {
    markdown += `- ${tech}\n`;
  });
  markdown += `\n`;

  if (prd.technicalStack.backend) {
    markdown += `### ${texts.labels.backend}\n`;
    prd.technicalStack.backend.forEach((tech) => {
      markdown += `- ${tech}\n`;
    });
    markdown += `\n`;
  }

  if (prd.technicalStack.database) {
    markdown += `### ${texts.labels.database}\n`;
    markdown += `- ${prd.technicalStack.database}\n\n`;
  }

  if (prd.technicalStack.hosting) {
    markdown += `### ${texts.labels.hosting}\n`;
    markdown += `- ${prd.technicalStack.hosting}\n\n`;
  }

  markdown += `### ${texts.labels.tooling}\n`;
  prd.technicalStack.tools.forEach((tool) => {
    markdown += `- ${tool}\n`;
  });
  markdown += `\n`;

  markdown += `## 📅 ${texts.headings.milestones}\n\n`;
  prd.milestones.forEach((milestone) => {
    markdown += `### ${milestone.phase} (${milestone.duration})\n`;
    milestone.deliverables.forEach((deliverable) => {
      markdown += `- [ ] ${deliverable}\n`;
    });
    markdown += `\n`;
  });

  markdown += `## 📊 ${texts.headings.successMetrics}\n\n`;
  prd.successMetrics.forEach((metric, index) => {
    markdown += `${index + 1}. ${metric}\n`;
  });
  markdown += `\n`;

  markdown += `---\n\n`;
  markdown += `*${texts.labels.generatedBy}*\n`;

  return markdown;
}

function getPrdLocaleTexts(language?: SupportedLanguage): IPrdLocaleTexts {
  const selectedLanguage: SupportedLanguage = language ?? 'en';
  return PRD_LOCALE_TEXTS[selectedLanguage];
}
