import type { ProjectConfig } from '../types';

export function generateRedisConfig(config: ProjectConfig): string {
  const lines: string[] = [
    "import Redis, { RedisOptions } from 'ioredis';",
    '',
    '// Redis configuration',
    'const redisConfig: RedisOptions = {',
    '  host: process.env.REDIS_HOST || "localhost",',
    '  port: parseInt(process.env.REDIS_PORT || "6379"),',
    '  password: process.env.REDIS_PASSWORD || undefined,',
    '  retryStrategy: (times: number) => {',
    '    const delay = Math.min(times * 50, 2000);',
    '    return delay;',
    '  },',
    '};',
    '',
    '// Create Redis client',
    "export const redis = new Redis(redisConfig);",
    '',
    '// Cache utilities',
    "export const cache = {",
    '  // Set a value with optional TTL (in seconds)',
    '  async set(key: string, value: string, ttl?: number): Promise<void> {',
    '    if (ttl) {',
    '      await redis.setex(key, ttl, value);',
    '    } else {',
    '      await redis.set(key, value);',
    '    }',
    '  },',
    '',
    '  // Get a value',
    '  async get(key: string): Promise<string | null> {',
    '    return redis.get(key);',
    '  },',
    '',
    '  // Delete a value',
    '  async delete(key: string): Promise<number> {',
    '    return redis.del(key);',
    '  },',
    '',
    '  // Check if key exists',
    '  async exists(key: string): Promise<boolean> {',
    '    const result = await redis.exists(key);',
    '    return result === 1;',
    '  },',
    '',
    '  // Increment a counter',
    '  async increment(key: string): Promise<number> {',
    '    return redis.incr(key);',
    '  },',
    '',
    '  // Set with rate limiting',
    '  async rateLimit(key: string, limit: number, windowSeconds: number): Promise<{ allowed: boolean; remaining: number }> {',
    '    const current = await redis.incr(key);',
    '    if (current === 1) {',
    '      await redis.expire(key, windowSeconds);',
    '    }',
    '    const remaining = Math.max(0, limit - current);',
    '    return {',
    '      allowed: current <= limit,',
    '      remaining,',
    '    };',
    '  },',
    '};',
    '',
    '// Session store utilities',
    "export const session = {",
    '  // Create session',
    '  async create(sessionId: string, data: Record<string, any>, ttl: number = 86400): Promise<void> {',
    `    await cache.set(\`session:\${sessionId}\`, JSON.stringify(data), ttl);`,
    '  },',
    '',
    '  // Get session',
    '  async get(sessionId: string): Promise<Record<string, any> | null> {',
    `    const data = await cache.get(\`session:\${sessionId}\`);`,
    '    return data ? JSON.parse(data) : null;',
    '  },',
    '',
    '  // Destroy session',
    '  async destroy(sessionId: string): Promise<void> {',
    `    await cache.delete(\`session:\${sessionId}\`);`,
    '  },',
    '',
    '  // Update session',
    '  async update(sessionId: string, data: Partial<Record<string, any>>): Promise<void> {',
    `    const existing = await session.get(sessionId);`,
    '    if (existing) {',
    `      await session.create(sessionId, { ...existing, ...data });`,
    '    }',
    '  },',
    '};',
    '',
    '// Graceful shutdown',
    'export async function closeRedis(): Promise<void> {',
    '  await redis.quit();',
    '}',
    '',
  ];

  return lines.join('\n');
}

export function generateSupabaseClient(config: ProjectConfig): string {
  const lines: string[] = [
    "import { createClient, SupabaseClient } from '@supabase/supabase-js';",
    '',
    '// Supabase configuration',
    'const supabaseUrl = process.env.SUPABASE_URL || "";',
    'const supabaseAnonKey = process.env.SUPABASE_ANON_KEY || "";',
    '',
    '// Create Supabase client',
    "export const supabase: SupabaseClient = createClient(supabaseUrl, supabaseAnonKey);",
    '',
    '// Database types (generate from your Supabase schema)',
    'export interface Database {',
    '  public: {',
    '    Tables: {',
    '      // Add your tables here',
    '      // Example:',
    '      // users: {',
    '      //   Row: {',
    '      //     id: string;',
    '      //     email: string;',
    '      //     name: string;',
    '      //     created_at: string;',
    '      //   };',
    '      //   Insert: {',
    '      //     id?: string;',
    '      //     email: string;',
    '      //     name: string;',
    '      //     created_at?: string;',
    '      //   };',
    '      //   Update: {',
    '      //     id?: string;',
    '      //     email?: string;',
    '      //     name?: string;',
    '      //     created_at?: string;',
    '      //   };',
    '      // };',
    '    };',
    '    Views: {',
    '      [_ in never]: never;',
    '    };',
    '    Functions: {',
    '      [_ in never]: never;',
    '    };',
    '    Enums: {',
    '      [_ in never]: never;',
    '    };',
    '  };',
    '}',
    '',
    '// Type helpers',
    'export type Tables<T extends keyof Database["public"]["Tables"]> =',
    '  Database["public"]["Tables"][T]["Row"];',
    '',
    'export type InsertTables<T extends keyof Database["public"]["Tables"]> =',
    '  Database["public"]["Tables"][T]["Insert"];',
    '',
    'export type UpdateTables<T extends keyof Database["public"]["Tables"]> =',
    '  Database["public"]["Tables"][T]["Update"];',
    '',
    '// Auth utilities',
    "export const auth = {",
    '  // Sign up',
    '  async signUp(email: string, password: string, metadata?: { [key: string]: any }) {',
    '    return await supabase.auth.signUp({',
    '      email,',
    '      password,',
    '      options: { data: metadata },',
    '    });',
    '  },',
    '',
    '  // Sign in',
    '  async signIn(email: string, password: string) {',
    '    return await supabase.auth.signInWithPassword({',
    '      email,',
    '      password,',
    '    });',
    '  },',
    '',
    '  // Sign out',
    '  async signOut() {',
    '    return await supabase.auth.signOut();',
    '  },',
    '',
    '  // Get current user',
    '  async getUser() {',
    '    return await supabase.auth.getUser();',
    '  },',
    '',
    '  // Get session',
    '  async getSession() {',
    '    return await supabase.auth.getSession();',
    '  },',
    '',
    '  // Reset password',
    '  async resetPassword(email: string) {',
    '    return await supabase.auth.resetPasswordForEmail(email, {',
    "      redirectTo: `${process.env.FRONTEND_URL}/reset-password`,",
    '    });',
    '  },',
    '};',
    '',
    '// Storage utilities',
    "export const storage = {",
    '  // Upload file',
    '  async upload(bucket: string, path: string, file: File | Blob) {',
    '    return await supabase.storage.from(bucket).upload(path, file);',
    '  },',
    '',
    '  // Get public URL',
    '  async getPublicUrl(bucket: string, path: string) {',
    '    return supabase.storage.from(bucket).getPublicUrl(path);',
    '  },',
    '',
    '  // Download file',
    '  async download(bucket: string, path: string) {',
    '    return await supabase.storage.from(bucket).download(path);',
    '  },',
    '',
    '  // Delete file',
    '  async delete(bucket: string, paths: string[]) {',
    '    return await supabase.storage.from(bucket).remove(paths);',
    '  },',
    '};',
    '',
    '// Realtime utilities',
    "export const realtime = {",
    '  // Subscribe to table changes',
    '  subscribe<T>(table: string, callback: (payload: T) => void) {',
    '    return supabase',
    `      .channel(\`public:\${table}\`)`,
    `      .on('postgres_changes', { event: "*", schema: "public", table }, (payload) => {`,
    '        callback(payload.new as T);',
    '      })',
    '      .subscribe();',
    '  },',
    '',
    '  // Unsubscribe',
    '  async unsubscribe(channel: ReturnType<typeof supabase.channel>) {',
    '    await supabase.removeChannel(channel);',
    '  },',
    '};',
    '',
  ];

  return lines.join('\n');
}

export function generateRedisDockerCompose(): string {
  return [
    '  redis:',
    '    image: redis:7-alpine',
    '    container_name: redis',
    '    ports:',
    '      - "6379:6379"',
    '    volumes:',
    '      - redis_data:/data',
    '    command: redis-server --appendonly yes',
    '    healthcheck:',
    '      test: ["CMD", "redis-cli", "ping"]',
    '      interval: 10s',
    '      timeout: 5s',
    '      retries: 5',
    '',
    'volumes:',
    '  redis_data:',
    '',
  ].join('\n');
}
